### ISSUE TITLE
物体在旋转时有万象节死锁问题

### ISSUE THREAD

**Issue by E11111s** [MambaCtrl/Some-of-EasyAR-s-Operations#1]
可以在物体外再套一个物体，用来控制上下转，里面的本物体控制左右转，取消外面物体的显示，初学者的一点小小想法。

**Comment by MambaCtrl** [comment]
good idea。有时间试一下

**Comment by MambaCtrl** [comment]
> 可以在物体外再套一个物体，用来控制上下转，里面的本物体控制左右转，取消外面物体的显示，初学者的一点小小想法。
>good idea。有时间可以试一试
